sudo: required
dist: trusty
addons:
  sonarqube:
    organization: garethahealy-github
    token:
      secure: GoNt6+017KWcbttQG7K7JpDvHaZZnuY7y0yfhw5nDFr3Es8U49ck8FcLhWGBKDn8txkerpIHnl9TsNRvSVV4kqat/bQfVRAhg284ojhVZRzYHISMQ3fYA61tY8eOW0GT8rm/dln0ciZJO+mOU/5nDLP8Fu1DLc7rdd8QtxRwdAM=
env:
  global:
  - secure: Otv56QwlwCuCDcLDG1dBFFZT0EVHCdQYJHEn9nfM1ZX+z+eJh7tA5qBrqajwm3lcX8UJrdK+3zXuTUCpf09bmrRnFk3sd6AUJusQsZbYGZn20Do0t8GukKnqGbZCR+gO6XK6Ri0OAemyK3qC0Is3+uw04edIAP7qSrVDh/iYh8I=
  - secure: MTTw/LOEaf4qsCCKZL6vTwfgsxCoMAfUvI9nMVRbJUzPBW4BKWvwSvoEVI+SOVf127VpNSbcmecSwKQRr44Uw59FbY09/fNxC5/e/dKmHPVd8DFlqZGX1J9ACTW6Oh7mvQhixDeeXTiySbniK5Eb/iuL4VyU4U9/Y1NVPNZrsaQ=
  - secure: JUY4tUZ3dtNbzeCYHBLsAvdlcKl01SeBiIjksMj3wZK+KjkhZ2EA+/M+pgwRouPxhHUtKYpjAPvLQyPCnOvtxvnMV288ChtzkjGcJy9fSMOo8hhn8LUBWoPlLYsYGnsEP3NftfiQO2EYOFb0pFZ1566CGq04dOwC6BAwz+hEqN4=
  - secure: MxmXCkb6BdABP89iF6uvPwsrseylPJdYow70nqQzWbxBKbihT2N9Q3FqjVmxxj0nIQM9fOd27kWVMkpNE+mzPAu0tEYuMm+dSfALhDmm/idHcH31uGd765AHtUKeGyuCFLRNHdV+VqzG5yxCqRwbS+ZTXo23gS/qhDyFMHjnSJ4=
language: java
jdk:
- oraclejdk8
before_install:
- bash .travis/deploy-codesigning.sh
install:
- bash .travis/update.sh
- export M2_HOME=/usr/share/maven3 && export PATH=${M2_HOME}/bin:${PATH} && export MAVEN_OPTS="-Xms2048m -Xmx2048m"
- java -version && javac -version && mvn -version -B
before_script:
- mvn dependency:resolve-plugins -B -Prelease-ossrh
script:
- mvn clean install -B
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -B
deploy:
  provider: script
  script: bash .travis/deploy.sh
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
cache:
  directories:
  - $HOME/.m2
  - $HOME/.victims
  - $HOME/.sonar/cache
